#-----------------------------------------------------------------------
#LIBCOMMON = libCommon.a


#TARGET := ${LIBCOMMON}

#
APP       := otim
TARGET    := libCommonTars.a
CONFIG    :=
STRIP_FLAG:= N
TARS2CPP_FLAG:=

#-------------------------------------------------------------------------------

#LIB     +=  -lhiredis -luuid  ../thrid/lib/libssl.a ../thrid/lib/libcrypto.a -L../../lib -lmsgstructpb -lprotobuf -lcommonjce -L/usr/lib64/mysql -lmysqlclient
#
#THIRDPATH  := ../third
#INCLUDE    += -I$(THIRDPATH) -I$(THIRDPATH)/curl/include -I../../pb -I../../CommonJCE -I/usr/include
#-------------------------------------------------------------------------------

#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
