// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 3.0.13.
// **********************************************************************

#ifndef __OTIM_CONST_H_
#define __OTIM_CONST_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
using namespace std;


namespace otim
{
    const std::string CONF_REDIS = "redis.conf";

    const std::string CONF_MYSQL = "mysql.conf";

    const std::string RKEY_CONN = "CLIENTCONN:";

    const std::string RKEY_HOTSESSION = "HOTSESSION:";

    const std::string RKEY_MSG = "MSG:";

    const std::string RKEY_MSG_HIGHPRJ = "MSGHIGHPRJ:";

    const std::string RKEY_UNREADCOUNT = "UNREADCOUNT:";

    const std::string RKEY_REPEATPACKID = "REPEATPACKID:";

    const std::string RKEY_GROUPINFO = "GROUPINFO:";

    const std::string RKEY_GROUPMEMBER = "GROUPMEMBER:";

    const std::string RKEY_MYGROUP = "MYGROUP:";

    const std::string RKEY_USERINFO = "USERINFO:";

    const std::string RKEY_FRIEND = "FRIEND:";

    const std::string RKEY_USERATTR = "USER_ATTR:";

    const std::string RKEY_SESSIONATTR = "SESSION_ATTR:";

    const std::string RKEY_TASKCACHE = "TASKCACHE:";


}



#endif
